### ISSUE TITLE
Whenever evil collection enabled, helm-find-files reports error invalid function helm-with-bufffer

### ISSUE THREAD

**Issue by iLLucionist** [emacs-evil/evil-collection#101]
Whenever I have this line enabled in `init.el`:

`(when (require 'evil-collection nil t) (evil-collection-init))`

Whenever I invoke `helm-find-files` it reports back with the error:

> Invalid function: with-helm-buffer

I have attached my `init.el`-file:

[init.el.txt](https://github.com/emacs-evil/evil-collection/files/1804418/init.el.txt)

**Comment by jojojames** [comment]
Hmnn, I'm not sure if there's a declare-macro equivalent. @Ambrevar @noctuid?

Wrapping the two functions with 'eval-when-compile eliminates the error but I'm not sure what the implications are beyond that. Maybe that's OK to do.

I added a commit to un-break this in the meantime.

**Comment by noctuid** [comment]
Macros need to be available at compile time, so there is no equivalent of `declare-function` as far as I am aware. Either helm is installed and successfully required, or there will be an error. You could put the macro definition in the file, but that's not a good solution. I think the only other way to prevent an error would be to not compile it at all if helm doesn't exist. If evil-collection is compiled before helm is installed, evil-collection with helm won't work properly; the error shouldn't just be silenced.

**Comment by Ambrevar** [comment]
My bad, I forgot it was a macro.

The solution is to be found upstream, I believe.
In short, `with-helm-buffer` is called from an override of
`helm--set-header-line`: I've basically copy-pasted the function just to
change a few lines.

It's dirty but Helm lacks flexibility at that level.  I'll see with @thierryvolpiatto.

**Comment by Ambrevar** [comment]
ddad9909fd9e6df01896fc0bbfc71c27c0675de1 should fix this.

**Comment by hlissner** [comment]
I am still getting this issue, but instead from `evil-collection-helm-hide-minibuffer-maybe` (which also uses `with-helm-buffer`). It occurs only on Emacs 25.3; not on 26 nor 27. Tested from a vanilla session of emacs (`emacs -Q --debug-init`) with:

```elisp
(setq evil-want-integration nil)
(require 'evil)
(require 'evil-collection)
(evil-collection-init)

(require 'helm)
(call-interactively 'helm-find-files)
```

Produces the following backtrace:

```
Debugger entered--Lisp error: (invalid-function with-helm-buffer)
  with-helm-buffer(nil)
  evil-collection-helm-hide-minibuffer-maybe()
  run-hooks(helm-minibuffer-set-up-hook)
  helm-log-run-hook(helm-minibuffer-set-up-hook)
  #[0 "\305\306!\210\307\301\206\300\206!\210\310\311!\210\302\312r\313 q\210\f)\314]\315\316#\240\210\317 \207" [nil (keymap (insert-state keymap "Auxiliary keymap for Insert state" (27 keymap (104 . helm-find-files-up-one-level)) (S-return . helm-ff-run-switch-other-window)) (normal-state keymap (68 . helm-ff-run-delete-file) (37 . helm-ff-run-query-repl
```

I'm currently using this workaround:

```diff
  (defun evil-collection-helm-hide-minibuffer-maybe ()
    "Hide text in minibuffer when `helm-echo-input-in-header-line' is non-nil."
-    (when (with-helm-buffer helm-echo-input-in-header-line)
+    (when (with-current-buffer (helm-buffer-get) helm-echo-input-in-header-line)
       (let ((ov (make-overlay (point-min) (point-max) nil nil t)))
```

**Comment by jojojames** [comment]
Is that a suitable workaround (for now?) @Ambrevar 

Maybe @hlissner can submit a PR for that workaround? I can also make the change if you'd prefer @hlissner.

Thanks!

**Comment by thierryvolpiatto** [comment]
I guess you just have an helm installation compiled with emacs 26 or 27 and you use it with 25, verify.
Anyway if the problem is that with-helm-buffer is not found, it is just an installation/compilation problem.
Lisp compiled files don't work with an emacs version < with the emacs version they were compiled with.
IOW if you compile files with emacs-25 they will work with emacs-26 but files compiled with emacs-26 will not work with emacs-25.

**Comment by Ambrevar** [comment]
I can't reproduce.  I suppose @thierryvolpiatto is right and it's a version conflict between byte-compiled code.
Anyways, @hlissner's fix does not cost anything so I'll apply it.  Thanks!

**Comment by Ambrevar** [comment]
Fixed in bca66d36fd7840284e553970ba9913e59521ef14.
